* Project 2 ("Tournament Results") Overview
  :PROPERTIES:
  :ID:       991A608A-3882-4B81-A0F4-C398ECC02C34
  :END:

Project 2 of the Udacity Fullstack Web Developer nanodegree course
involves writing Python code that interacts with a PostgreSQL
database.

I have used two different code bases, contained in the directories
~meets-spec~ and ~exceeds-spec~, to meet the requirements laid out in
the project description. One is concerned with simply /meeting/ these
requirements. See [[id:8D697589-2E12-432A-A1D0-F8675736137F][Tournament Results project (Meets Specifications
version)]], within the ~meets specs~ directory.


The second collection is a comparatively rough draft of an extension
to the basic functionality provided by the ~meets specs~ code. That
is, there are several features (originally mentioned in the design
specs as "exceeding" specifications, though this mention was
ultimately removed from the specs) that would significantly extend the
relatively limited functionality provided by the ~meets spec~
codebase.

These features, provided by both Python and psql code, are fully
documented in the README in the ~exceeds spec~ directory. Please see
[[id:44BCAC8C-C972-42B3-9166-E0BA720CABFE][Project 2 ("Tournament Results") EXCEEDS SPECIFICATIONS code overview]]

** Potential Problems

For the code in ~exceeds spec~, there are not "tests," per se.

While the tests for the ~meets spec~ code are relatively
straightfoward (and in fact did not have to be written by this
developer but were already given), devising tests for the ~exceeds
spec~ proved extremely problematic.

Indeed, trying to come up with a viable test suite for them largely
caused me to postpone submitting all the other code till now, even
though it was all written months ago.

Nonetheless, I submit all the code related to the "exceeds
specifications" features with some documentation and a kind of "test
file" ([[file:exceeds-spec/core/tournament_demonstration.py][tournament_demonstration.py]]) that should show that it in fact
works for basic use cases. Writing a full-fledged test suite, however,
would needlessly delay my progress even further.

