* Project 2 ("Tournament Results") Overview
Project 2 of the Udacity Fullstack Web Developer nanodegree course
involves writing Python code that interacts with a PostgreSQL
database.

I have used two different code bases, contained in the directories
~meets-spec~ and ~exceeds-spec~ to meet the requirements laid out in
the project description. One is concerned with simply meeting the
requirements of the specifications provided by Udacity; it is
contained within the ~meets specs~ directory, and is documented by a
README therein.

The second collection is a comparatively rough draft of an extension
to the basic functionality provided by the ~meets specs~ code. That
is, there are several features (originally mentioned in the design
specs as "exceeding" specifications, though this mention was
ultimately removed from the specs) that would significantly extend the
relatively limited functionality provided by the ~meets spec~
codebase.

These features, provided by both Python and psql code, are fully
documented in the README in the ~exceeds spec~ directory

** Problems

*For the code in ~exceeds spec~, there are not "tests," per se*

While the tests for ~meets spec~ code are relatively straightfoward--
and in fact did not have to be written by this developer but were in
fact already given--devising tests for the ~exceeds spec~ proved
extremely problematic.

In fact, trying to come up with a viable test suite for them largely
caused me to postpone submitting all the other code till now, even
though it was all written months ago.

Nonetheless, I submit all the code related to the "exceeds
specifications" features with documentation and a kind of "test file"
([[file:exceeds-spec/core/tournament_demonstration.py][tournament_demonstration.py]]) that should show that it in fact works
for basic use cases. Writing a full-fledged test suite, however, would
needlessly delay my progress even further.

