* TOC
** I. Introduction                                                               
** II. Anatomy of a Nanodegree                                                   
                                                                               
  Projects and Courses                                                          
                                                                               
  Deadlines                                                                     
                                                                               
  Career Development                                                            
                                                                               
  Community                                                                     
                                                                               
  Time Commitment                                                               
                                                                               
** III. Nanodegree Roadmap                                                       
                                                                               
  Enrollment Requirements                                                       
                                                                               
  Program Timeline and Project Portfolio                                        
                                                                               
  Project Submission and Graduation                                             
                                                                               
  Previously Earned Verified Certificates                                       
                                                                               
  How do I maintain good standing in the program?                               
                                                                               
  Honor Code                                                                    
                                                                               
  Nanodegree Program                                                            
                                                                               
  Project Submissions                                                           
                                                                               
  Community Guidelines                                                          
                                                                               
** IV. Nanodegree Support System                                                 
                                                                               
  Community Forum                                                               
                                                                               
  Events and Google+ Communities                                                
                                                                               
  Webcasts                                                                      
                                                                               
  One-on-one Appointments                                                       
                                                                               
** V. Payment Policy and Cancellations                                           
                                                                               
  Free Trials                                                                   
                                                                               
  Cancellations and Refunds                                                     
                                                                               
  Pausing a Nanodegree                                                          
                                                                               
  More Questions?                                                               
                                                                               
* I. Introduction                                                               
                                                                               
 Welcome to Udacity’s Full Stack Web Developer Nanodegree program! After       
 reading this document, you should understand the requirements and policies of 
 the Nanodegree, where completing the program will take you, and how to get    
 support when you need it.                                                     
                                                                               
 Please read this whole document carefully before you begin, and if you still  
 have questions at the end, feel free to contact us in the forum or at         
 fullstack-support@udacity.com.                                                
                                                                               
 Once again, welcome, and we can’t wait to see what you achieve!               
                                                                               
 Happy learning,                                                               
                                                                               
 The Udacity Team                                                              
                                                                               
* II. Anatomy of a Nanodegree
                                                                               
 A Nanodegree consists of a series of courses and projects designed to help    
 you develop job-relevant skills and build a portfolio to show prospective     
 employers. Udacity designed the Full Stack Web Developer Nanodegree           
 curriculum through close work with industry partners and experts alike.       
                                                                               
 Together with your cohort, you will learn how to build complex server-side    
 web applications that make use of powerful relational databases to            
 persistently store data using these tools: Python, Flask, Google API          
 endpoints and SQLite. Additionally, you will learn about other tools and      
 platforms used by web developers in the tech industry today, including Git    
 and Github.                                                                   
                                                                               
 Projects and Courses                                                          
                                                                               
 The bulk of the Nanodegree consists of completing five projects, accompanied  
 by courses. These courses are designed to help you prepare to work on your    
 projects, but they are not mandatory (unless otherwise noted). More           
 information is provided in Section III: Nanodegree Roadmap. You can see a     
 list of these projects and courses in your Udacity Home.                      
                                                                               
 Deadlines                                                                     
                                                                               
 To help your pace yourself, each project has its own deadline -- a date by    
 which the project must be submitted -- that you’ll need to reach in order to  
 stay with your current cohort. You’ll find your deadlines in your Udacity     
 Home.                                                                         
                                                                               
 Career Development                                                            
                                                                               
 Career development, in addition to technical growth, is an important part of  
 the Nanodegree program. Udacity’s career development support includes:        
                                                                               
 * One-on-one feedback on your resume, LinkedIn, and GitHub profiles, and      
   feedback as you prepare for behavioral and technical interviews.            
 *                                                                             
 * Career Development Workshops with industry experts touching on topics like  
   salary negotiation.                                                         
 * One-on-one career appointments and email support to help you work through   
   any career questions you have.                                              
 * Introductions to employers and recruiters through Udacity Talent Source. To 
   take part in this program, make sure you fill out your Udacity Profile      
   fully to best show off your talents to Udacity partner employers.           
 * Access to Udactiy's Career Resource Center and its library of helpful       
   articles, videos, and workshops.                                            
                                                                               
 Community                                                                     
                                                                               
 One of the biggest benefits of the Nanodegree experience is being part of a   
 cohort and completing the program with hundreds of other students from around 
 the world. Though not all students may move through the curriculum at exactly 
 the same pace, your Nanodegree community will be your strongest resource and  
 support system. We expect you to be active in your community, as outlined in  
 the Honor Code.                                                               
                                                                               
 Time Commitment                                                               
                                                                               
 We designed this Nanodegree so that you can graduate in 6-9 months, assuming  
 you devote at least 10 hours per week to learning and working on the required 
 projects. Students are welcome to finish the Nanodegree program in as little  
 as two months (our minimum required commitment for eligibility to graduate)   
 if they are able to commit more than the minimum time to learn the material   
 and complete the projects.                                                    
                                                                               
* III. Nanodegree Roadmap
                                                                               
 Enrollment Requirements                                                       
                                                                               
 This Nanodegree has several important criteria that you should have met       
 before enrolling in the program. Please make sure you have already done each  
 of the following:                                                             
                                                                               
 1 Taken the Readiness Assessment to determine if you are ready to pursue the  
   Nanodegree.                                                                 
 2 Fulfilled all prerequisites, as listed on the Full Stack Web Developer      
   Nanodegree overview page.                                                   
 3 Made sure your system satisfies Udacity’s Technology Requirements.          
                                                                               
 If you have not done all of these things, please do them right away. If you   
 realize you are not prepared to begin the program at this time, please        
 unsubscribe from the Nanodegree before your 7-day free trial ends. You will   
 be able to reenroll with a later cohort after you have fulfilled the          
 prerequisites. We cannot guarantee a refund for students on account of        
 unpreparedness.                                                               
                                                                               
 If you currently have little to no programming experience, we recommend       
 taking a look at the courseware for Intro to Computer Science for a thorough  
 understanding of foundational computer science concepts before you begin a    
 Nanodegree.                                                                   
                                                                               
 Program Timeline and Project Portfolio                                        
                                                                               
 Graduating from the Nanodegree requires that you submit work that meets       
 Udacity’s specifications for six particular projects. You can find the        
 timeline for your cohort, as well as a roadmap for what you’ll work on in the 
 program, in your Udacity Home.                                                
                                                                               
 If you are not able to meet a deadline, you will automatically be moved to a  
 later cohort based on your progress and activity in the Nanodegree program.   
 Students who submit one of the two projects due will be moved back one        
 cohort; students who do not submit either of the projects due will be moved   
 back two cohorts. As a courtesy, students who have been inactive since the    
 last deadline will be unenrolled from the program unless they request         
 otherwise.                                                                    
                                                                               
 Project Submission and Graduation                                             
                                                                               
 You will submit each project you complete to Udacity for evaluation using     
 your Udacity Home . Detailed submission instructions for each project are     
 listed in its project info sections, accessible by clicking the project’s     
 name in the Udacity Home.                                                     
                                                                               
 You can submit projects as soon as your first payment has been received. Once 
 we’ve received and begun to process your project submission, you will receive 
 a confirmation email. Due to the high volume of submissions, the turnaround   
 period for project evaluations is 1 week. While waiting for the evaluation to 
 be returned, you are welcome to start working on your next project.           
                                                                               
 You may be required to do a verification interview with a Udacity Coach to    
 verify that the project in question represents your own work and/or correctly 
 cites all sources and reasons for using others’ code in any part of your      
 submission. For verification purposes, you will be asked to provide a         
 government-issued ID during your graduation process.                          
                                                                               
 Previously Earned Verified Certificates                                       
                                                                               
 If you have successfully completed the project for the Programming            
 Foundations with Python course in the past (which entails having graduated    
 from the course and having access to your course certificate), simply email   
 us at fullstack-support@udacity.com to notify us.                             
                                                                               
 To become a verified graduate of the Full Stack Developer Nanodegree Program, 
 you must:                                                                     
                                                                               
 * Successfully complete all projects in the Project Portfolio for the         
   Nanodegree, earning a “Meets Specifications” or above for all projects      
 * Schedule and pass any requested verification interviews                     
 * Maintain good standing for the duration of the program                      
 * Stay in the program longer than one month past the Free Trial window        
                                                                               
 How do I maintain good standing in the program?                               
                                                                               
 To maintain good standing and stay in the program, students are expected to   
 meet the following criteria:                                                  
                                                                               
 * Abide by the Udacity Honor Code, the Terms of Service, and the terms        
   outlined in this Full Stack Web Developer Nanodegree Student Handbook       
 * If asked, schedule an exit interview within 7 days                          
                                                                               
 The requirements above are designed to help students graduate from the Full   
 Stack Web Developer Nanodegree Program within 6-9 months of enrollment or     
 earlier. Students who do not maintain good standing will be asked to leave    
 the program.                                                                  
                                                                               
 Honor Code                                                                    
                                                                               
 Nanodegree Program                                                            
                                                                               
 * I will abide by the Terms of Service, Student Handbook guidelines, and all  
   components of the Honor Code set for Udacity Nanodegree participants.       
 * I will conduct myself with honor as part of the Udacity community.          
 * I understand that all decisions regarding participation, graduation, and    
   awarding of verified certificates will be made by Udacity at its sole       
   discretion.                                                                 
                                                                               
 Project Submissions                                                           
                                                                               
 * I hereby confirm that all project submissions consist of my own work.       
   Accordingly, I will document and cite the origins of any part(s) of my      
   project submissions that were taken from websites, books, forums, blog      
   posts, github repositories, or any other source and explain why I used them 
   for any part of my submission. I understand that I may be asked to explain  
   my work in a video call with a Udacity Coach before my Nanodegree is        
   conferred.                                                                  
                                                                               
 Community Guidelines                                                          
                                                                               
 * I will help cultivate a positive, supportive learning environment.          
 * I will communicate respectfully and considerately with all other Nanodegree 
   participants, Udacity Coaches, and Udacity representatives.                 
 * I will not share any content that is obscene, illicit, threatening, or      
   discriminatory.                                                             
 * I will contribute constructively to discussions with fellow students.       
 * I will notify a Udacity Coach immediately if I become aware of cheating or  
   plagiarism by any Nanodegree student.                                       
                                                                               
* IV. Nanodegree Support System
                                                                               
 Community Forum                                                               
                                                                               
 Each Nanodegree program has its own Udacity Discussions forum where students  
 can ask and answer each other’s questions about the projects, program         
 logistics, and course material. Udacity Coaches also moderate posts, answer   
 student questions, and publicize important program information in this forum. 
 Coaches do their best to ensure all content-related questions have answers    
 within twenty-four hours.                                                     
                                                                               
 To access the forum, click the Discussions link from any classroom page in    
 your Nanodegree. Then click the “Log In” button in the upper right hand       
 corner to be automatically signed in.                                         
                                                                               
 Events and Google+ Communities                                                
                                                                               
 Nanodegree students have access to content, community, and career events      
 integral to their learning experience through Google Hangouts On Air hosted   
 in the Full Stack Web Dev Nanodegree Google+ Community. To join this          
 community, each student needs to have or create a Google+ account under the   
 name listed on your Udacity profile.                                          
                                                                               
 Webcasts                                                                      
                                                                               
 Codecasts are live, 15 to 45-minute sessions in which Udacity instructors     
 provide in-depth explanations of final projects, as well as supplementary     
 resources related to full stack web development. You can access these events  
 through your cohort’s Google+ Community, and a recording of each session will 
 be available afterward.                                                       
                                                                               
 If you are unable to make a live broadcast, you are welcome to submit         
 questions you have in advance and come back to hear them answered when it’s   
 convenient for you.                                                           
                                                                               
 One-on-one Appointments                                                       
                                                                               
 The Udacity Coach team is available for 20-minute one-on-one appointments on  
 a first come, first served basis. The purpose of these meetings is to help    
 answer in-depth content-related questions that you cannot get answers to      
 elsewhere.                                                                    
                                                                               
 In-depth instructions on how to book a one-on-one appointment are available   
 in your Udacity Home.                                                         
                                                                               
* Payment Policy and Cancellations
                                                                               
Free Trials                                                                   
                                                                               
All Nanodegree programs start with a 7-day free trial (more precisely, seven  
24-hour cycles), during which time you will have full access to all           
Nanodegree features.                                                          
                                                                               
You are required to enter your credit card information at the time of         
enrollment but will not be billed until after your free trial expires. After  
this, you will automatically be charged a fee of $200 per month for your      
Nanodegree subscription.                                                      
                                                                               
Cancellations and Refunds                                                     
                                                                               
If you opt to cancel your enrollment within the one-week Free Trial window,   
you will not be charged, regardless of how far you have come in the program.  
We strongly recommend that you complete the Readiness Assessment before the   
one-week Free Trial window expires to make sure that the Nanodegree is a good 
fit for you.                                                                  
                                                                               
Students who cancel will no longer be charged the monthly subscription fee,   
effective the next billing cycle from the date of cancellation. Students who  
wish to cancel after the Free Trial expires will not be granted a refund for  
the past month’s subscription fees.                                           
                                                                               
Pausing a Nanodegree                                                          
                                                                               
Due to the open nature of our courses combined with the pacing of the         
Nanodegree, Udacity cannot pause active subscriptions. However, we understand 
that our students are very busy and that life can take unexpected turns,      
which may not always leave enough time to continue the Nanodegree program at  
the required pace.                                                            
                                                                               
As you move through your Nanodegree, all of your progress is automatically    
saved. Thus, if you feel that you need to take a break from the program at    
any point, you are welcome to cancel your subscription and then re-enroll     
during a future open registration period when you are ready to return. You’ll 
be able to pick up right where you left off! Based on your overall progress   
in a Nanodegree, you may also be moved to an earlier cohort upon request      
after you re-enroll.                                                          
                                                                               
More Questions?                                                               
                                                                               
We are actively working on ways to improve the Full Stack Web Developer       
Nanodegree. Please be aware that we may make adjustments throughout your time 
in the program based on student and industry feedback. We will notify active  
Nanodegree students about any impact this may have on their experience or     
program requirements.                                                         
                                                                               
If you have any unanswered questions, please email                            
fullstack-support@udacity.com!                                                

